/* Automatically generated by './build/bin/build-entry.js' */
import config from '../package.json'
import PlTableColumn from '../packages/pl-table-column/index.js';
import PlTable from '../packages/pl-table/index.js';
import PlxTableGrid from '../packages/plx-table-grid/index.js';
import PlxTableColumn from '../packages/plx-table-column/index.js';
import locale from 'pl-table/src/locale';
const components = [
  PlTableColumn,
  PlTable,
  PlxTableGrid,
  PlxTableColumn
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: config.version,
  locale: locale.use,
  i18n: locale.i18n,
  install,
  PlTableColumn,
  PlTable,
  PlxTableGrid,
  PlxTableColumn
};
